version: "3.8"

services:
  ci4:
    build: .
    container_name: ci4-apache
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
    environment:
      - CI_ENVIRONMENT=development
      - DEV_PORT=8080
      - URLAPISERVER=http://aciraba-server:1111/
    networks:
      - aciraba-net

networks:
  aciraba-net:
    external: true
